# Generated by Django 5.2 on 2025-04-27 13:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kapitan',
            fields=[
                ('id_kapitana', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Numer telefonu musi mieć 9 cyfr.', regex='^\\d{9}$')])),
                ('potwierdzony', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='kolejka',
            fields=[
                ('id_kolejki', models.AutoField(primary_key=True, serialize=False)),
                ('numer', models.IntegerField()),
                ('nazwa', models.CharField(blank=True, max_length=100)),
                ('data_rozpoczecia', models.DateTimeField()),
                ('data_zakonczenia', models.DateTimeField()),
                ('czy_zakonczona', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['numer'],
            },
        ),
        migrations.CreateModel(
            name='liga',
            fields=[
                ('id_ligi', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=50)),
                ('poziom_rozgrywkowy', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('liczba_zespolow', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='uzytkownik',
            fields=[
                ('id_uzytkownika', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('haslo_hash', models.CharField(max_length=128)),
                ('typ_uzytkownika', models.CharField(choices=[('organizator', 'Organizator'), ('kapitan', 'Kapitan'), ('fan', 'Fan')], default='fan', max_length=20)),
                ('data_rejestracji', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='druzyna',
            fields=[
                ('id_druzyny', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=50)),
                ('herb_url', models.URLField(blank=True)),
                ('data_rejestracji', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('oczekujaca', 'oczekujaca'), ('zatwierdzona', 'zatwierdzona'), ('odrzucona', 'odrzucona')], default='oczekujaca', max_length=20)),
                ('punkty', models.IntegerField(default=0)),
                ('bramki_zdobyte', models.IntegerField(default=0)),
                ('bramki_stracone', models.IntegerField(default=0)),
                ('id_kapitana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawodowplaner.kapitan')),
            ],
        ),
        migrations.CreateModel(
            name='mecz',
            fields=[
                ('id_meczu', models.AutoField(primary_key=True, serialize=False)),
                ('data_meczu', models.DateTimeField()),
                ('wynik_gospodarz', models.IntegerField(default=0)),
                ('wynik_gosc', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('planowany', 'planowany'), ('rozpoczety', 'rozpoczety'), ('zakonczony', 'zakonczony')], default='planowany', max_length=20)),
                ('sedzia_glowny', models.CharField(max_length=50)),
                ('miejsce', models.CharField(max_length=100)),
                ('druzyna_gosc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='druzyna_gosc', to='zawodowplaner.druzyna')),
                ('druzyna_gospodarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='druzyna_gospodarz', to='zawodowplaner.druzyna')),
                ('id_kolejki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawodowplaner.kolejka')),
            ],
        ),
        migrations.CreateModel(
            name='powiadomienie',
            fields=[
                ('id_powiadomienia', models.AutoField(primary_key=True, serialize=False)),
                ('tresc', models.TextField()),
                ('data_wyslania', models.DateTimeField(auto_now_add=True)),
                ('przeczytane', models.BooleanField(default=False)),
                ('typ', models.CharField(choices=[('systemowe', 'systemowe'), ('rejestracja', 'rejestracja'), ('mecz', 'mecz')], max_length=20)),
                ('id_uzytkownika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawodowplaner.uzytkownik')),
            ],
        ),
        migrations.CreateModel(
            name='organizator',
            fields=[
                ('id_organizatora', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Numer telefonu musi mieć 9 cyfr.', regex='^\\d{9}$')])),
                ('PESEL', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='PESEL musi mieć 11 cyfr.', regex='^\\d{11}$')])),
                ('data_dolaczenia', models.DateTimeField(auto_now_add=True)),
                ('id_uzytkownika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawodowplaner.uzytkownik')),
            ],
        ),
        migrations.AddField(
            model_name='kapitan',
            name='id_uzytkownika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawodowplaner.uzytkownik'),
        ),
        migrations.CreateModel(
            name='zawodnik',
            fields=[
                ('id_zawodnika', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('data_urodzenia', models.DateField()),
                ('pozycja', models.CharField(choices=[('bramkarz', 'Bramkarz'), ('obronca', 'Obrońca'), ('pomocnik', 'Pomocnik'), ('napastnik', 'Napastnik')], max_length=50)),
                ('numer_koszulki', models.IntegerField()),
                ('zdjecie_url', models.URLField(blank=True)),
                ('id_druzyny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawodowplaner.druzyna')),
            ],
        ),
        migrations.CreateModel(
            name='wydarzenie',
            fields=[
                ('id_wydarzenia', models.AutoField(primary_key=True, serialize=False)),
                ('minuta', models.IntegerField()),
                ('typ', models.CharField(choices=[('bramka', 'Bramka'), ('kartka_zolta', 'Kartka Żółta'), ('kartka_czerwona', 'Kartka Czerwona'), ('zmiana', 'Zmiana'), ('rzut_karny', 'Rzut Karny')], max_length=20)),
                ('komentarz', models.TextField(blank=True)),
                ('id_druzyny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawodowplaner.druzyna')),
                ('id_meczu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawodowplaner.mecz')),
                ('id_zawodnika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawodowplaner.zawodnik')),
            ],
        ),
        migrations.CreateModel(
            name='zawody',
            fields=[
                ('id_zawodu', models.AutoField(primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=50)),
                ('data_rozpoczecia', models.DateTimeField()),
                ('data_zakonczenia', models.DateTimeField()),
                ('status', models.CharField(choices=[('oczekujaca', 'oczekujaca'), ('zatwierdzona', 'zatwierdzona'), ('odrzucona', 'odrzucona'), ('anulowane', 'Anulowane')], default='planowane', max_length=20)),
                ('opis', models.TextField()),
                ('czy_otwarta', models.BooleanField(default=False)),
                ('maks_zespolow', models.IntegerField()),
                ('regulaminy', models.TextField()),
                ('id_ligi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawodowplaner.liga')),
                ('id_organizatora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawodowplaner.organizator')),
            ],
        ),
        migrations.AddField(
            model_name='mecz',
            name='id_zawodu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawodowplaner.zawody'),
        ),
        migrations.AddField(
            model_name='kolejka',
            name='id_zawodu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawodowplaner.zawody'),
        ),
        migrations.AddField(
            model_name='druzyna',
            name='id_zawodu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawodowplaner.zawody'),
        ),
        migrations.AlterUniqueTogether(
            name='kolejka',
            unique_together={('id_zawodu', 'numer')},
        ),
    ]
