# Generated by Django 5.2 on 2025-04-28 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zawodowplaner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='druzyna',
            old_name='data_rejestracji',
            new_name='data_utworzenia',
        ),
        migrations.RemoveField(
            model_name='druzyna',
            name='bramki_stracone',
        ),
        migrations.RemoveField(
            model_name='druzyna',
            name='bramki_zdobyte',
        ),
        migrations.RemoveField(
            model_name='druzyna',
            name='id_zawodu',
        ),
        migrations.RemoveField(
            model_name='druzyna',
            name='punkty',
        ),
        migrations.RemoveField(
            model_name='druzyna',
            name='status',
        ),
        migrations.CreateModel(
            name='zgloszenie',
            fields=[
                ('id_zgloszenia', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('oczekujaca', 'Oczekująca'), ('zatwierdzona', 'Zatwierdzona'), ('odrzucona', 'Odrzucona')], default='oczekujaca', max_length=20)),
                ('data_rejestracji', models.DateTimeField(auto_now_add=True)),
                ('punkty', models.IntegerField(default=0)),
                ('bramki_zdobyte', models.IntegerField(default=0)),
                ('bramki_stracone', models.IntegerField(default=0)),
                ('id_druzyny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawodowplaner.druzyna')),
                ('id_zawodu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawodowplaner.zawody')),
            ],
            options={
                'unique_together': {('id_zawodu', 'id_druzyny')},
            },
        ),
        migrations.AlterField(
            model_name='mecz',
            name='druzyna_gosc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goscie', to='zawodowplaner.zgloszenie'),
        ),
        migrations.AlterField(
            model_name='mecz',
            name='druzyna_gospodarz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gospodarze', to='zawodowplaner.zgloszenie'),
        ),
    ]
