# Generated by Django 5.2 on 2025-05-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zawodowplaner', '0002_alter_uzytkownik_is_active_alter_uzytkownik_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='username',
            field=models.CharField(default='default_user', max_length=150, unique=True),
        ),
    ]
