# Generated by Django 5.2 on 2025-04-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zawodowplaner', '0002_rename_data_rejestracji_druzyna_data_utworzenia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zawody',
            name='id_ligi',
        ),
        migrations.DeleteModel(
            name='liga',
        ),
    ]
