# Generated by Django 5.2 on 2025-04-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zawodowplaner', '0003_remove_zawody_id_ligi_delete_liga'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='druzyna',
            options={'verbose_name': 'Drużyna', 'verbose_name_plural': 'Drużyny'},
        ),
        migrations.AlterModelOptions(
            name='kapitan',
            options={'verbose_name': 'Kapitan', 'verbose_name_plural': 'Kapitanowie'},
        ),
        migrations.AlterModelOptions(
            name='kolejka',
            options={'ordering': ['numer'], 'verbose_name': 'Kolejka', 'verbose_name_plural': 'Kolejki'},
        ),
        migrations.AlterModelOptions(
            name='mecz',
            options={'verbose_name': 'Mecz', 'verbose_name_plural': 'Mecze'},
        ),
        migrations.AlterModelOptions(
            name='organizator',
            options={'verbose_name': 'Organizator', 'verbose_name_plural': 'Organizatorzy'},
        ),
        migrations.AlterModelOptions(
            name='powiadomienie',
            options={'verbose_name': 'Powiadomienie', 'verbose_name_plural': 'Powiadomienia'},
        ),
        migrations.AlterModelOptions(
            name='uzytkownik',
            options={'verbose_name': 'Użytkownik', 'verbose_name_plural': 'Użytkownicy'},
        ),
        migrations.AlterModelOptions(
            name='wydarzenie',
            options={'verbose_name': 'Wydarzenie', 'verbose_name_plural': 'Wydarzenia'},
        ),
        migrations.AlterModelOptions(
            name='zawodnik',
            options={'verbose_name': 'Zawodnik', 'verbose_name_plural': 'Zawodnicy'},
        ),
        migrations.AlterModelOptions(
            name='zawody',
            options={'verbose_name': 'Zawody', 'verbose_name_plural': 'Zawody'},
        ),
        migrations.AlterModelOptions(
            name='zgloszenie',
            options={'verbose_name': 'Zgłoszenie', 'verbose_name_plural': 'Zgłoszenia'},
        ),
    ]
