# Generated by Django 5.2 on 2025-04-28 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zawodowplaner', '0004_alter_druzyna_options_alter_kapitan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecz',
            name='wynik_gosc',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='mecz',
            name='wynik_gospodarz',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='wydarzenie',
            name='minuta',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
