# Generated by Django 5.2 on 2025-04-28 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zawodowplaner', '0005_alter_mecz_wynik_gosc_alter_mecz_wynik_gospodarz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizator',
            name='imie',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Imię nie może zawierać cyfr.', regex='^[^\\d]*$')]),
        ),
        migrations.AlterField(
            model_name='organizator',
            name='nazwisko',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Nazwisko nie może zawierać cyfr.', regex='^[^\\d]*$')]),
        ),
    ]
