# Generated by Django 5.2 on 2025-04-28 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zawodowplaner', '0006_alter_organizator_imie_alter_organizator_nazwisko'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizator',
            name='id_uzytkownika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawodowplaner.uzytkownik', unique=True),
        ),
    ]
