# Generated by Django 5.2 on 2025-04-28 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zawodowplaner', '0007_alter_organizator_id_uzytkownika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wydarzenie',
            name='minuta',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='Minuta nie może być mniejsza niż 0.'), django.core.validators.MaxValueValidator(120, message='Minuta nie może być większa niż 120.')]),
        ),
    ]
