# Generated by Django 5.2 on 2025-04-28 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zawodowplaner', '0008_alter_wydarzenie_minuta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizator',
            name='id_uzytkownika',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zawodowplaner.uzytkownik'),
        ),
    ]
