# Generated by Django 5.2 on 2025-04-29 18:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zawodowplaner', '0009_alter_organizator_id_uzytkownika'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zawodnik',
            name='imie',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Imię może zawierać tylko litery.')]),
        ),
        migrations.AlterField(
            model_name='zawodnik',
            name='nazwisko',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[a-zA-Z]+$', 'Nazwisko może zawierać tylko litery.')]),
        ),
        migrations.AlterField(
            model_name='zawodnik',
            name='numer_koszulki',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='bramki_stracone',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='bramki_zdobyte',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='zgloszenie',
            name='punkty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
